object_classes:

  #--------------------------------------------------------------------------------------------
  # for car category 
  #--------------------------------------------------------------------------------------------
  car:
    keypoints_num: 12
    object_keypoints_mean:
      [-0.568, 0.568, 0.482, -0.482, -0.582,
      0.582, 0.702, -0.702, -0.805, -0.805,
      0.805, 0.805,
      -0.253, -0.253, 1.570, 1.570, -1.988,
      -1.988, 1.961, 1.961, -1.286, 1.355,
      -1.286, 1.355,
      1.331, 1.331, 1.331, 1.331, 0.702,
      0.702, 0.924, 0.924, 0.329, 0.329,
      0.329, 0.329]
    object_mean_shape:
      [1.6, 3.9, 1]
    aliases:
      - truck
      - bus
      - van
    marker_color: [0.0, 0.0, 0.0]
    # color is black 

  #--------------------------------------------------------------------------------------------
  # for bicycle category 
  #--------------------------------------------------------------------------------------------

  bicycle:
    keypoints_num: 11
    object_keypoints_mean:
      [-1.70808127e-04,  -1.50001940e-01,   1.49998060e-01,
         -2.81705415e-02,   2.92172366e-02,  -1.72628652e-04,
         -1.55280115e-05,  -3.59743247e-02,   3.24773351e-02,
         -4.51876315e-02,   3.94705946e-02,
       -5.44494399e-01,  -5.57207036e-01,  -5.59112866e-01,
         -8.99557479e-01,  -8.99540561e-01,   6.89689240e-01,
          1.30573382e-01,   9.00442521e-01,   8.94981261e-01,
          7.94408375e-02,   8.24049428e-02,
       6.78173161e-01,   6.59279873e-01,   6.58873971e-01,
         -2.86543426e-01,  -2.86444976e-01,   5.80824071e-01,
          5.95945049e-01,  -2.77740430e-01,  -2.78488707e-01,
         -3.21826839e-01,  -3.18725364e-01]
    object_mean_shape:
      [0.3, 1.8, 1.0]
    aliases: []
    marker_color: [1.0, 0.0, 0.0]
    # red 

  #--------------------------------------------------------------------------------------------
  # for chair category 
  #--------------------------------------------------------------------------------------------

  chair:
    keypoints_num: 10
    object_keypoints_mean:
      [-0.16260029, -0.18636511,  0.16428348,  0.18096888, -0.174444  ,
            -0.19166636,  0.1767874 ,  0.18786542, -0.19818088,  0.19658388,
      0.17052046,  0.13219248,  0.17011265,  0.13199527, -0.19604203,
            -0.21056669, -0.19605567, -0.20875473,  0.19473798,  0.19352854,
      -0.44795494, -0.00819907, -0.44773116, -0.00803745, -0.44755495,
            -0.01097987, -0.44755495, -0.01101388,  0.55173099,  0.55204506]
    object_mean_shape:
      [0.4, 0.4, 1]
    aliases:
      - bench
    marker_color: [0.0, 0.0, 1.0]
    # blue 

#--------------------------------------------------------------------------------------------
# other configs 
#--------------------------------------------------------------------------------------------

# whether to fine tune object pose using Levenberg Marquardt
# do_fine_tune_object_pose_using_lm: false 
do_fine_tune_object_pose_using_lm: true       

# The directory where result files are saved per object
result_dir_path_object_map: "/home/erl/Workspace/orcvio_cpp/cache/object_map/"

# The directory where bounding boxes are saved 
result_dir_path_2d_bbox: "/home/erl/Workspace/orcvio_cpp/cache/object_2d_bbox_info.txt"
